begin;

delete from public.company_trades;
delete from public.companies;
delete from public.azubi_profiles;
delete from public.profiles;

delete from public.trades;

insert into public.trades (name) values
('Anlagenmechaniker/in'),
('Anlagenmechaniker/in für Sanitär-, Heizungs- und Klimatechnik'),
('Asphaltbauer/in'),
('Augenoptiker/in'),
('Ausbaufacharbeiter/in'),
('Automatenfachmann/-frau'),
('Automobilkaufmann/-frau'),
('Bäcker/in'),
('Bankkaufmann/-frau'),
('Baugeräteführer/in'),
('Baustoffprüfer/in'),
('Behälter- und Apparatebauer/in'),
('Beton- und Stahlbetonbauer/in'),
('Biologielaborant/in'),
('Bodenleger/in'),
('Bootsbauer/in'),
('Brauer und Mälzer/in'),
('Brunnenbauer/in'),
('Buchhändler/in'),
('Büchsenmacher/in'),
('Chemielaborant/in'),
('Chemikant/in'),
('Dachdecker/in'),
('Destillateur/in'),
('Drogist/in'),
('Drucker/in'),
('Duales Studium Handel'),
('Duales Studium Technik'),
('Eisenbahner/in im Betriebsdienst'),
('Elektroniker/in'),
('Elektroniker/in für Automatisierungstechnik'),
('Elektroniker/in für Betriebstechnik'),
('Elektroniker/in für Energie- und Gebäudetechnik'),
('Elektroniker/in für Geräte und Systeme'),
('Elektroniker/in für Gebäudesystemintegration'),
('Elektroniker/in für Informations- und Systemtechnik'),
('Estrichleger/in'),
('Fachinformatiker/in'),
('Fachkraft für Abwassertechnik'),
('Fachkraft für Gastronomie'),
('Fachkraft für Hafenlogistik'),
('Fachkraft für Kreislauf- und Abfallwirtschaft'),
('Fachkraft für Kurier-, Express- und Postdienstleistungen'),
('Fachkraft für Lagerlogistik'),
('Fachkraft für Lebensmitteltechnik'),
('Fachkraft für Metalltechnik'),
('Fachkraft für Möbel-, Küchen- und Umzugsservice'),
('Fachkraft für Rohr-, Kanal- und Industrieservice'),
('Fachkraft für Schutz und Sicherheit'),
('Fachkraft für Straßen- und Verkehrstechnik'),
('Fachkraft für Veranstaltungstechnik'),
('Fachlagerist/in'),
('Fachmann/-frau für Restaurants und Veranstaltungsgastronomie'),
('Fachmann/-frau für Systemgastronomie'),
('Fahrzeuglackierer/in'),
('Feinoptiker/in'),
('Feinwerkmechaniker/in'),
('Fleischer/in'),
('Fliesen-, Platten- und Mosaikleger/in'),
('Florist/in'),
('Fotograf/in'),
('Friseur/in'),
('Gebäudereiniger/in'),
('Geomatiker/in'),
('Gerüstbauer/in'),
('Gießereimechaniker/in'),
('Glaser/in'),
('Goldschmied/in'),
('Gleisbauer/in'),
('Handelsfachwirt/in'),
('Hauswirtschafter/in'),
('Hochbaufacharbeiter/in'),
('Holzmechaniker/in'),
('Hotelfachmann/-frau'),
('Hotelkaufmann/-frau'),
('Immobilienkaufmann/-frau'),
('Industrieelektriker/in'),
('Industriemechaniker/in'),
('Industriekaufmann/-frau'),
('Informationselektroniker/in'),
('IT-System-Elektroniker/in'),
('Justizfachangestellte/r'),
('Kanalbauer/in'),
('Karosserie- und Fahrzeugbaumechaniker/in'),
('Kaufmann/-frau für Büromanagement'),
('Kaufmann/-frau für Dialogmarketing'),
('Kaufmann/-frau für Digitalisierungsmanagement'),
('Kaufmann/-frau für E-Commerce'),
('Kaufmann/-frau für Groß- und Außenhandelsmanagement'),
('Kaufmann/-frau für IT-System-Management'),
('Kaufmann/-frau für Marketingkommunikation'),
('Kaufmann/-frau für Spedition und Logistikdienstleistung'),
('Kaufmann/-frau für Tourismus und Freizeit'),
('Kaufmann/-frau im Einzelhandel'),
('Kaufmann/-frau im Gesundheitswesen'),
('Kfz-Mechatroniker/in'),
('Klempner/in'),
('Koch/Köchin'),
('Konditor/in'),
('Konstruktionsmechaniker/in'),
('Lacklaborant/in'),
('Land- und Baumaschinenmechatroniker/in'),
('Lebensmitteltechniker/in'),
('Luftverkehrskaufmann/-frau'),
('Maler/in und Lackierer/in'),
('Maschinen- und Anlagenführer/in'),
('Maurer/in'),
('Mechatroniker/in'),
('Mechatroniker/in für Kältetechnik'),
('Mediengestalter/in Bild und Ton'),
('Mediengestalter/in Digital und Print'),
('Medienkaufmann/-frau Digital und Print'),
('Metallbauer/in'),
('Mikrotechnologe/in'),
('Naturwerksteinmechaniker/in'),
('Oberflächenbeschichter/in'),
('Packmitteltechnologe/in'),
('Parkettleger/in'),
('Personaldienstleistungskaufmann/-frau'),
('Pferdewirt/in'),
('Pharmakant/in'),
('Physiklaborant/in'),
('Produktionsfachkraft Chemie'),
('Produktionstechnologe/in'),
('Raumausstatter/in'),
('Restaurantfachmann/-frau'),
('Rohrleitungsbauer/in'),
('Rollladen- und Sonnenschutzmechatroniker/in'),
('Schifffahrtskaufmann/-frau'),
('Schilder- und Lichtreklamehersteller/in'),
('Schornsteinfeger/in'),
('Servicefachkraft für Dialogmarketing'),
('Sport- und Fitnesskaufmann/-frau'),
('Straßenbauer/in'),
('Stuckateur/in'),
('Süßwarentechnologe/in'),
('Technische/r Modellbauer/in'),
('Technische/r Produktdesigner/in'),
('Technische/r Systemplaner/in'),
('Technischer Modellbauer/in'),
('Textil- und Modenäher/in'),
('Tiefbaufacharbeiter/in'),
('Tischler/in'),
('Tourismuskaufmann/-frau'),
('Trockenbaumonteur/in'),
('Uhrmacher/in'),
('Veranstaltungskaufmann/-frau'),
('Verfahrensmechaniker/in'),
('Verkäufer/in'),
('Wärme-, Kälte- und Schallschutzisolierer/in'),
('Werkstoffprüfer/in'),
('Werkzeugmechaniker/in'),
('Zerspanungsmechaniker/in'),
('Zimmerer/Zimmerin'),
('Zweiradmechatroniker/in');

commit;
